### ISSUE TITLE
No Data Layer gets put on top of stack when Color Bar layer is present

### ISSUE THREAD

**Issue by knowles** [seadas/seadas#67]
Open a smi file
Open a band
View the Layer Manager window.

Toggle "No-Data Layer" and observe that it gets put near the stack bottom below the Masks and Vector folders.  This is normal.

Now add a Color Bar layer.

Now toggle "No-Data Layer" and it gets put at the top of the stack, obscuring anything such as masks and pins below in the layer stack. 

The gridlines and blue-marble layers don't cause trouble.

There is something about the Color Bar layer existing which causes No-Data to be put at the top of the stack.

**Comment by aynur** [comment]
Can't reproduce. Maybe it's fixed with issue #69. Please confirm that this bug is fixed.

**Comment by knowles** [comment]
This bug is not fixed when I tested it out.    Look at the layer manager when you toggle no-data on/off.

**Comment by aynur** [comment]
Fixed. Modified the "getNoDataLayer(boolean create) method in ProductSceneImage.java to add the no-data layer at the bottom of layers.

**Comment by knowles** [comment]
Probably results from this fix but I found the case where if there is a no-data layer and color bar layer, then you save a session, close it, reopen the session it complains.  

You click ok.  Then the session opens, but in the layer manager the Vector folder and Mask folder are gone as well as the no-data layer and colorbar layer.

**Comment by knowles** [comment]
Just raising the label status on this as it currently causes a more significant session reload failure bug when no-data layer and color bar layer both exist.

**Comment by knowles** [comment]
Verified as fixed.  There is an issue in that a saved session which occurred previously in this bug state won't open.   But we just need to consider that this previous session file is corrupt.
